version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wisper-fast-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uv run /app/whisper_api.py
